function Xprime = QuadRotor(t, X, flag, u)
% X = [x, y, z, phi (phi1), theta (phi2), psi (phi3), dot{x}, dot{y}, dot{z}, p, q, r, omega1, omega2, omega3, omega4]

global m grav L I k_F k_m k_M wh G

phi = X(4:6);
omega = X(13:16);
F = k_F * omega.^2;
M = k_M * omega.^2;

T = [cos(phi(2)), 0, -cos(phi(1))*sin(phi(2)); ...
    0, 1, sin(phi(1)); ...
    sin(phi(2)), 0, cos(phi(1))*cos(phi(2))];

Rotation_matrix = [cos(phi(3))*cos(phi(2)) - sin(phi(1))*sin(phi(3))*sin(phi(2)), -cos(phi(1))*sin(phi(3)), cos(phi(3))*sin(phi(2)) + cos(phi(2))*sin(phi(1))*sin(phi(3)); ...
    sin(phi(3))*cos(phi(2)) + sin(phi(1))*cos(phi(3))*sin(phi(2)), cos(phi(1))*cos(phi(3)), sin(phi(3))*sin(phi(2)) - cos(phi(2))*sin(phi(1))*cos(phi(3)); ...
    -cos(phi(1))*sin(phi(2)), sin(phi(1)), cos(phi(1))*cos(phi(2))];

Xprime = [X(7:9); ...
    T\X(10:12); ...
    [0, 0, -grav]' + Rotation_matrix * [0, 0, sum(F)/m]'; ...
    I\([L*(F(2) - F(4)), L*(F(3) - F(1)), M(1) - M(2) + M(3) - M(4)]' - cross(X(10:12), I*X(10:12))); ...
    k_m*(wh*ones(4,1) - omega)] + G * ppval(u, t);